# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
user = User.create( { email: "ngoc120742@gmail.com", name: "Nguyen Thi Bao Ngoc", dob: "1995/12/07", password: "1234567" ,confirmed_at: DateTime.now } )
blog = Blog.create( [{tittle: "About my day", content: "
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce consequat, est ut vulputate congue, massa velit accumsan libero, quis convallis velit nisl eu odio. Maecenas varius sapien quis turpis aliquet tempus. Nunc pharetra elementum nulla a sagittis. Nullam in hendrerit metus, ut volutpat enim. Donec purus velit, imperdiet elementum lacus nec, lacinia convallis mauris. Duis volutpat orci ut quam gravida, eget dignissim dui vestibulum. Praesent faucibus tristique tortor, eu pretium ex ultrices quis. Praesent eu ipsum facilisis, viverra ipsum id, posuere purus. Mauris non convallis tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Quisque quis diam mollis, ultricies nunc ut, tristique nunc. In vitae ex vitae enim aliquam accumsan at vel est.

Nulla gravida neque aliquam ligula ullamcorper, in pulvinar justo tempor. Vivamus nec elit eros. Vivamus vehicula leo nec ante porta, et tincidunt ipsum malesuada. Nulla et massa vel ligula suscipit tristique eu in est. Donec erat est, tempus ut dui vitae, gravida lobortis diam. Mauris eros tortor, mattis at purus vel, rutrum tincidunt diam. Duis vulputate varius mi at scelerisque. Vivamus mattis, enim sed congue finibus, purus leo tincidunt ipsum, ac scelerisque est turpis in eros. Cras rhoncus iaculis tellus, quis tempus diam suscipit ac. Sed a dolor leo. Quisque eleifend hendrerit felis, sit amet varius nisl placerat a. Quisque sollicitudin sem vel magna imperdiet, dictum vulputate magna lobortis. Etiam elit ligula, commodo ut diam et, molestie tempor felis.

Etiam eleifend tempus nisl nec sagittis. Suspendisse pulvinar felis eu mattis euismod. Quisque rutrum quam in tempor tempus. Nullam molestie sagittis massa mattis pretium. Quisque vel gravida velit, non rhoncus nisl. Maecenas non laoreet leo. Sed ligula erat, tincidunt sit amet magna nec, tincidunt consequat risus. Curabitur porta vel mi id malesuada. Nam viverra sapien at egestas tincidunt. Nunc ac venenatis tellus. Phasellus erat nibh, fermentum ornare lacus fermentum, feugiat pellentesque leo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam a est sed tortor aliquet efficitur.

Aenean semper velit consequat, ultricies sapien id, molestie ipsum. Vestibulum ante turpis, posuere vel leo a, ultricies ornare ligula. Suspendisse elementum tincidunt justo, et laoreet augue euismod ac. Duis nec urna malesuada lorem placerat tincidunt ac at nisl. Morbi sed congue dui. Nulla facilisis enim nec pulvinar ornare. Duis sed urna et neque placerat luctus nec eu quam.

In eleifend enim maximus tincidunt scelerisque. Sed ex massa, pellentesque ut euismod in, mattis id tortor. Vivamus interdum convallis risus, in ornare erat condimentum et. Donec at convallis massa, hendrerit porta felis. Quisque neque nunc, eleifend id sem ultricies, volutpat interdum odio. Curabitur nisl nulla, mollis egestas bibendum et, fermentum at lectus. Praesent convallis lectus a nisl eleifend, quis finibus lorem ultrices. Cras tincidunt nec libero et ultrices. Mauris et rhoncus metus, quis ultrices velit. Donec nisl tortor, cursus vel purus a, porttitor lacinia lectus. Cras ultricies viverra euismod. Sed tristique in eros quis porta. Praesent non facilisis diam, nec luctus tortor.", view:0, user_id: 1, imgcover: "/IMG_1166.jpg"},
{tittle: "About my day", content: "
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce consequat, est ut vulputate congue, massa velit accumsan libero, quis convallis velit nisl eu odio. Maecenas varius sapien quis turpis aliquet tempus. Nunc pharetra elementum nulla a sagittis. Nullam in hendrerit metus, ut volutpat enim. Donec purus velit, imperdiet elementum lacus nec, lacinia convallis mauris. Duis volutpat orci ut quam gravida, eget dignissim dui vestibulum. Praesent faucibus tristique tortor, eu pretium ex ultrices quis. Praesent eu ipsum facilisis, viverra ipsum id, posuere purus. Mauris non convallis tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Quisque quis diam mollis, ultricies nunc ut, tristique nunc. In vitae ex vitae enim aliquam accumsan at vel est.

Nulla gravida neque aliquam ligula ullamcorper, in pulvinar justo tempor. Vivamus nec elit eros. Vivamus vehicula leo nec ante porta, et tincidunt ipsum malesuada. Nulla et massa vel ligula suscipit tristique eu in est. Donec erat est, tempus ut dui vitae, gravida lobortis diam. Mauris eros tortor, mattis at purus vel, rutrum tincidunt diam. Duis vulputate varius mi at scelerisque. Vivamus mattis, enim sed congue finibus, purus leo tincidunt ipsum, ac scelerisque est turpis in eros. Cras rhoncus iaculis tellus, quis tempus diam suscipit ac. Sed a dolor leo. Quisque eleifend hendrerit felis, sit amet varius nisl placerat a. Quisque sollicitudin sem vel magna imperdiet, dictum vulputate magna lobortis. Etiam elit ligula, commodo ut diam et, molestie tempor felis.

Etiam eleifend tempus nisl nec sagittis. Suspendisse pulvinar felis eu mattis euismod. Quisque rutrum quam in tempor tempus. Nullam molestie sagittis massa mattis pretium. Quisque vel gravida velit, non rhoncus nisl. Maecenas non laoreet leo. Sed ligula erat, tincidunt sit amet magna nec, tincidunt consequat risus. Curabitur porta vel mi id malesuada. Nam viverra sapien at egestas tincidunt. Nunc ac venenatis tellus. Phasellus erat nibh, fermentum ornare lacus fermentum, feugiat pellentesque leo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam a est sed tortor aliquet efficitur.

Aenean semper velit consequat, ultricies sapien id, molestie ipsum. Vestibulum ante turpis, posuere vel leo a, ultricies ornare ligula. Suspendisse elementum tincidunt justo, et laoreet augue euismod ac. Duis nec urna malesuada lorem placerat tincidunt ac at nisl. Morbi sed congue dui. Nulla facilisis enim nec pulvinar ornare. Duis sed urna et neque placerat luctus nec eu quam.

In eleifend enim maximus tincidunt scelerisque. Sed ex massa, pellentesque ut euismod in, mattis id tortor. Vivamus interdum convallis risus, in ornare erat condimentum et. Donec at convallis massa, hendrerit porta felis. Quisque neque nunc, eleifend id sem ultricies, volutpat interdum odio. Curabitur nisl nulla, mollis egestas bibendum et, fermentum at lectus. Praesent convallis lectus a nisl eleifend, quis finibus lorem ultrices. Cras tincidunt nec libero et ultrices. Mauris et rhoncus metus, quis ultrices velit. Donec nisl tortor, cursus vel purus a, porttitor lacinia lectus. Cras ultricies viverra euismod. Sed tristique in eros quis porta. Praesent non facilisis diam, nec luctus tortor.", view:0, user_id: 1, imgcover: "/cat.jpg"}])
image= Image.create([{user_id: 1, url: "/assets/1412350.jpg", view: 0}, {user_id: 1, url: "/assets/1412322.jpg", view: 0}])
album= Album.create({user_id: 1, totalview: 0, imgcover: "/assets/1412350.jpg", name: "ngoc"})